# Generated by Django 5.2.1 on 2025-05-31 00:08

import api.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('state', models.IntegerField(choices=[(1, 'Available'), (2, 'Sold'), (3, 'Reserved')], default=api.enums.StateEnum['Available'])),
                ('type', models.IntegerField(choices=[(1, 'Apartment'), (2, 'House'), (3, 'Land'), (4, 'Commercial'), (5, 'Other')], default=api.enums.TypeEnum['Apartment'])),
                ('image', models.ImageField(default=None, null=True, upload_to='properties/')),
                ('visibility_level', models.IntegerField()),
                ('street', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=200)),
                ('longtitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('size_m2', models.IntegerField()),
                ('energy_rating', models.CharField(max_length=1)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
    ]
